### ISSUE TITLE
default ingress syntax conflicts in kra up versus appstore

### ISSUE THREAD

**Issue by aep** [kraudcloud/cli#21]
```yaml
service
  labels:
     - kr.ingress.http.80=${INGRESS:-https://nextcloud.dev.*}
   
x-kraud-ui:
 config:
    INGRESS:
      kind: "ingress"
      label: "web UI domain"
      description: Domain where the app will be hosted.
      protocol: "https"
      default: "nextcloud"

```

kra up:
```
Error: failed to generate pod: failed to parse labels: invalid ingress label: nextcloud. should start with https:// or tcp://
```

which would make sense but the appstore requires it to be __not__ prefixed with https://
